require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '22505943319',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0EwQmZQTy93bFRtN2VycDJ2cTI2Qng0TWU3d1phbUNUVFp2N1Z2T0RYQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMW1kNWRKcnZrczVBVE1wMWNzZm94MnhQelN3aGJoQk4zZVZhUnF2Uld4OD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4TGZxQURPM2pTRURURmFLK0NkcE90V2VKQllTckM5Yjd6aW00YTJITVVNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCQWQrR1ZvVjRQbEtpOFdBbU9YQXd1SnRxc3JNZ1NNelZKeHR4WWI1djA4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklDTEdQVGZrSnhiYy9vQ0ErdGNYUHBpYzVOaTF4alJZckdkRTdoTjFWSHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZRNnFPcmMyZngrU2ZCOThvcFMxOEdnMmx1MTBlaTV6a0Rzckk1SXB1Q289In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU54aXlmc1B1dGJZMms2cDllMmNUY1ZaSXVvd3ozRDNGcG1XWmpHQjMwaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibVN1NUIvVlM3Q2wwbUVUTHExNnMvaGNIOURiR3Mwa3d2aUV6NmtWNnJUcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkcxNWtIa3ZjM2VRSXArTUJSZ1lkdHBLWWJ3SW5COWVoMFJTNDNHZHBmcWRMNVcwMG16TEw2K3VZLzVBQTU1S045Nm0rN2F6VnJWN3pkSUp2S1lvNGp3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDgsImFkdlNlY3JldEtleSI6IkNCTTdXaTMxQWVTdkVwVmM4U3ZzRitKc2hNdmIwd2tkMWRkTXFZcUlWVG89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjI1OTQzMzE5MjJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOEFCMkQwN0FEOTcyODdENjkyMzlCMUU0QTA0Q0E2RUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MDU0MzY3M30seyJrZXkiOnsicmVtb3RlSmlkIjoiMjI1OTQzMzE5MjJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQ0I5MzE1MEI3M0Q5NzA4Q0U0RDYxMzlBOEU5QUMyREMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MDU0MzY3NX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiQ0hNN0VEQ0ciLCJtZSI6eyJpZCI6IjIyNTk0MzMxOTIyOjM1QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjcwMDcxMjM0NzI1MTI6MzVAbGlkIiwibmFtZSI6IuqngUwnSU5TU0FJU1NBQkxF8JKGnEJFTEdF6qeCIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPS0JrTllIRUtYYTNNSUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI0bjlXTzJQV2w4WmhybnJMc2xvT3ExaHZ4RXJjY0J1VVBsY2JVdWJHcGhJPSIsImFjY291bnRTaWduYXR1cmUiOiJUeG5uSERmMkh4aDNkcTg1bXR0SUV0SUJTWXpBWktKNlltZEZEUDZOUjF1bHZKQ24xL0wzc2V4SVFrTDdWOC8wbUg5NERlOTV3U3AzZ1FQdzVUVFpCZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiOVJ5T29iQnM0dlZtVHZwWHJWSlk3T1ZBNWJSbE00alZvWU5wMnNXZGwzQ2UrUzVFUjltY3NzSG1kcmpVZ2JZV0l5WTFzZFo3M0ZISWFTVGF4Tm5nZ3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMjU5NDMzMTkyMjozNUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJlSi9WanRqMXBmR1lhNTZ5N0phRHF0WWI4UkszSEFibEQ1WEcxTG14cVlTIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQUlJQ0E9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTA1NDM2NjcsImxhc3RQcm9wSGFzaCI6IjJQMVloZiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSi9VIn0=',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || null,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
